### PR TITLE
Changing plugin to the right naming convention

### PR DESCRIPTION
**Pull request by mamazu**
Making the plugin compatible with the correct naming convention. This requires the plugin to be renamed so you might also need to update the packagist information.

### CODE REVIEW

**Comment by lchrusciel** [comment]
Thank you very much! But according to rest of our plugins (e.g. https://github.com/Sylius/RefundPlugin) we should rather drop the `Sylius` from the repo name than changing all namespaces. 

/cc @pamil

**Comment by pamil** [comment]
We decided not to apply that naming convention in Sylius' plugins, as it would result in repeating `Sylius` both in repository name and organisation name. I guess we should update the convention to explicitly say it's for 3rd party plugins.

**Comment by mamazu** [comment]
So then the merge request is closed? And ticket #263 is also invalid?

**Comment by lchrusciel** [comment]
Yup, lets close both

**Pull request closed without merging**
