### PR TITLE
Fix errors in swagger file

### PR DESCRIPTION
**Pull request by alexander-schranz**
The https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0 is not up2date and the exist swagger.yml in doc/swagger.yml has same errors in it when copy it to https://editor.swagger.io/

### CODE REVIEW

**Comment by mamazu** [comment]
Yes, the api documentation on swaggerhub is currently not up to date as it is not Synchronized with the documentation of the main repository.

**Comment by lchrusciel** [comment]
Thank you, Alexander! :1st_place_medal:

**Comment by alexander-schranz** [comment]
@lchrusciel thx for merging. Is it possible to update the swaggerhub file on the current one is kind of outdated missing some endpoints (e.g. register, password forget, ..): https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0

**Comment by lchrusciel** [comment]
For now, I have opened an issue. I will try to do something about it

**Comment by mamazu** [comment]
If there is an API for it we could use the github actions feature.

**Pull request merged**
