### PR TITLE
Add onHand to product response

### PR DESCRIPTION
**Pull request by alexander-schranz**
It should be possible to know how many products are still available.

### CODE REVIEW

**Comment by mamazu** [comment]
Could you rebase this onto the current master?

**Comment by alexander-schranz** [comment]
@mamazu all rebased

**Comment by mamazu** [comment]
Thanks, Alexander! :tada:

**Comment by alexander-schranz** [comment]
@mamazu Thank you :)

**Comment by mamazu** [comment]
Thanks for the contribution.

**Pull request merged**
