### PR TITLE
Cleanup swagger.yml from remains ChannelCode parameters

### PR DESCRIPTION
**Pull request by diimpp**

### CODE REVIEW

**Comment by mamazu** [comment]
I think we should remove the whole `#/parameters/ChannelCode` definition.

**Comment by diimpp** [comment]
Done

**Comment by diimpp** [comment]
@mamazu ping :)

**Comment by lchrusciel** [comment]
Hello Dimitri, 

thank a lot for PR. Just to let you know, I have checkouted it and forced pushed version rebased to the master.

**Comment by lchrusciel** [comment]
Thank you, Dmitri! :tada:

**Pull request merged**
