### PR TITLE
missing email_verification_token fix (#359)

### PR DESCRIPTION
**Pull request by aayaresko**
issue #359

### CODE REVIEW

**Comment by mamazu** [comment]
As far as I know the command bus flushes everything anyways after executing the middle ware.

**Comment by aayaresko** [comment]
okay, I'll check that on my local machine one more time.

**Comment by aayaresko** [comment]
no, sir. the email_verification_token is empty without that line...

**Comment by aayaresko** [comment]
could you please check the registration flow so we both would know that there is no need to update the code of the plugin an everything works as expected

**Comment by mamazu** [comment]
Sure thing.

**Comment by aayaresko** [comment]
> Sure thing.

thanx a lot!

**Comment by mamazu** [comment]
Hm, I can't find where the command service is configured. Could you have a look. The compiler doesn't seem to generate the service definition. Do you have a service definition for "command.bus"?

**Comment by aayaresko** [comment]
no, I don't

**Comment by aayaresko** [comment]
okay, let's see...

**Comment by aayaresko** [comment]
found what's causing it. another config for tactician overrides the one from the SyliusShopApi

**Comment by aayaresko** [comment]
closing the request

**Pull request closed without merging**
