### PR TITLE
adding company and phoneNumber to checkout/address

### PR DESCRIPTION
**Pull request by hashnz**

### CODE REVIEW

**Comment by mamazu** [comment]
Are those options now required or are they optional?

**Comment by hashnz** [comment]
@mamazu they should be optional, there's a test here that doesn't pass them in https://github.com/Sylius/ShopApiPlugin/blob/762ecd752154e97d1ce42a3c2dc8a3da572c6e8f/tests/Controller/Checkout/CheckoutSummarizeApiTest.php#L112

**Comment by dlobato** [comment]
new fields are not reflected on swagger definition

**Comment by hashnz** [comment]
@dlobato thanks, I've added those

**Comment by mamazu** [comment]
Thanks, Matt! :tada:

**Pull request merged**
