### PR TITLE
Compatibility with Sylius 1.2.x

### PR DESCRIPTION
**Pull request by Gounlaf**
It seems that just updating composer do the job.

### CODE REVIEW

**Comment by lchrusciel** [comment]
According to [composer semantic versioning](https://getcomposer.org/doc/articles/versions.md#caret-version-range-), the current notation is correct. `^1.1` means that every version in range ">1.1.0 <2.0.0" is allowed. 

Did you notice any issues with Sylius 1.2?

Anyway, closing an issue.

**Comment by Gounlaf** [comment]
> Did you notice any issues with Sylius 1.2?

Yup, composer won't install this dependency. I will check again why. I may forgot to add the version `@beta`

**Comment by lchrusciel** [comment]
I hope it won't be issue for long :D

**Comment by Gounlaf** [comment]
Good evening @lchrusciel,

Sorry for the inconvenience... problem came from my setup.
Don't know why; I've done a fresh install and reinstalled all dependencies... and it works.

**Comment by lchrusciel** [comment]
Oh, it is my fault in the end. I have to publish a new version, sorry :(

**Comment by lchrusciel** [comment]
Can you try it once more?

**Comment by Gounlaf** [comment]
On a fresh install it still doesn't work.
But if I add "manually" the dependency in `composer.json` and do an update, it downgrade symfony from 4.x to 3.x

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 16 updates, 1 removal
  - Removing symfony/class-loader (v3.4.15)
  - Updating zendframework/zend-stdlib (3.2.0 => 3.2.1): Downloading (100%)         
  - Downgrading symfony/symfony (v4.1.4 => v3.4.15): Downloading (100%)         
  - Installing symfony/polyfill-apcu (v1.9.0): Downloading (100%)         
  - Updating swiftmailer/swiftmailer (v6.1.2 => v6.1.3): Downloading (100%)         
  - Updating symfony/swiftmailer-bundle (v3.2.2 => v3.2.3): Downloading (100%)         
  - Updating ocramius/proxy-manager (2.1.1 => 2.2.1): Downloading (100%)         
  - Updating knplabs/gaufrette (v0.6.0 => v0.7.0): Downloading (100%)         
  - Downgrading behat/mink (dev-master d5ee350 => v1.7.1):  Checking out e6930b9c74
  - Updating phpunit/phpunit (6.5.12 => 6.5.13): Downloading (100%)         
  - Updating symplify/package-builder (v4.6.1 => v4.7.0): Downloading (100%)         
  - Updating symplify/better-phpdoc-parser (v4.6.1 => v4.7.0): Downloading (100%)         
  - Updating composer/xdebug-handler (1.2.1 => 1.3.0): Loading from cache
  - Updating symplify/token-runner (v4.6.1 => v4.7.0): Downloading (100%)         
  - Updating symplify/coding-standard (v4.6.1 => v4.7.0): Downloading (100%)         
  - Updating slevomat/coding-standard (4.7.0 => 4.7.3): Downloading (100%)         
  - Updating nette/robot-loader (v3.0.4 => v3.1.0): Downloading (100%)         
  - Updating symplify/easy-coding-standard (v4.6.1 => v4.7.0): Downloading (100%)         
  - Installing league/tactician (v1.0.3): Downloading (100%)         
  - Installing league/tactician-doctrine (v1.1.1): Downloading (100%)         
  - Installing league/tactician-bundle (v0.4.1): Downloading (100%)         
  - Installing sylius/shop-api-plugin (v1.0.0-beta.20): Downloading (100%)         
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

What about running composer thanks now?
This will spread some 💖  by sending a ★  to 160 GitHub repositories of your fellow package maintainers.

> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

                                                                                
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------------ ------------------ 
      Bundle                         Method / Error    
 --- ------------------------------ ------------------ 
  ✔   SonataCoreBundle               relative symlink  
  ✔   WhiteOctoberPagerfantaBundle   relative symlink  
 --- ------------------------------ ------------------ 

                                                                                
 [OK] All assets were successfully installed.                                   
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

**Comment by lchrusciel** [comment]
`sylius/shop-api-plugin (v1.0.0-beta.20)` is still a wrong version. It should be 21

**Comment by Gounlaf** [comment]
> `sylius/shop-api-plugin (v1.0.0-beta.20)` is still a wrong version. It should be 21

It seems that Packagist is not aware about last tags (checked at the moment of writhing this comment here https://packagist.org/packages/sylius/shop-api-plugin)

**Comment by lchrusciel** [comment]
Try it now, I just have updated packagist

**Comment by Gounlaf** [comment]
@lchrusciel It's working with beta 21 :)

**Pull request closed without merging**
