### PR TITLE
Update AddProductReviewByCodeRequest.php

### PR DESCRIPTION
**Pull request by aike-ps**
Fix bug. Rating must be only Int.

### CODE REVIEW

**Comment by mamazu** [comment]
Could you please merge this together with the other merge request you did.

**Comment by mamazu** [comment]
One thing I am thinking about is that you cahnged the default value. With `get` the default value if the property does not exist is `null` and the default value of `getInt` is `0` so there is no way of differenticating between not rated and rated very badly.

**Comment by aike-ps** [comment]
now not working at all, good luck )))

**Comment by aike-ps** [comment]
```
AddProductReviewByCode
 public function __construct(
        string $productCode,
        string $channelCode,
        string $title,
        **int $rating,**
        string $comment,
        string $email
    )
```

**Comment by mamazu** [comment]
Thanks for pointing that out. Yes the store rating hast to be an integer but the fact that field is filled with something other than null should be validated at the request level. So if you create a review without giving it a rating then the validator should return a 400 and never trigger the command.

**Pull request closed without merging**
