### PR TITLE
[Address] Handle adress exists validation in case when address does not belong to any customer

### PR DESCRIPTION
**Pull request by hurricane-voronin**
Hi there, 
I've got an error during validation of address existence in case when it does not belong to any customer:
see `AddressExistsValidator`
```php
if ($address->getCustomer()->getEmail() !== $user->getEmail()) {
    return $this->context->addViolation($constraint->message);
}
```

### CODE REVIEW

**Comment by mamazu** [comment]
Hey,
thanks for your contribution. This looks like an issue that should be fixed. Would you mind, to add tests for you new behaviour?

**Comment by diimpp** [comment]
Fixes https://github.com/Sylius/ShopApiPlugin/issues/705

**Comment by mamazu** [comment]
I have pushed tests to this branch and it is ready to be merged.

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Denys! :1st_place_medal:

**Pull request merged**
