### PR TITLE
Revert "Add onHand to product response"

### PR DESCRIPTION
**Pull request by lchrusciel**
Reverts Sylius/ShopApiPlugin#503

### CODE REVIEW

**Comment by mamazu** [comment]
What's the problem with that?

**Comment by alexander-schranz** [comment]
@mamazu As mentioned in #508 we should expose only `availability` flag and not how many are onHand or onHold. As I think onHand and onHold could be also sensitive data for a shop or?

**Comment by mamazu** [comment]
There are two reasons why they should be reverted:
1. the availability is based on more factors than just on hand and on hold quantity.
2. @lchrusciel and I agreed that this might not be part of the 1.1 version as currently we are in a feature freeze phase.

**Comment by alexander-schranz** [comment]
@mamazu
1. yeah thats what I wanted to say.
2. you mean not part of 1.0?

**Comment by mamazu** [comment]
Yes, currently we are just trying to stabalize the current version and not introduce any new features.

**Comment by mamazu** [comment]
Thanks, Łukasz! :tada:

**Pull request merged**
