### PR TITLE
Removed unused cart controller

### PR DESCRIPTION
**Pull request by mamazu**
I found an old controller that is not used anymore. So we can safely remove it.

### CODE REVIEW

**Comment by pamil** [comment]
Looks like it is used indeed - https://travis-ci.org/Sylius/SyliusShopApiPlugin/jobs/418205962#L818.

**Comment by mamazu** [comment]
Ok, it looks odd. Maybe we should refactor it.

**Comment by lchrusciel** [comment]
Remove item should be removed for 100%. Delivery cost estimation should be saved, but I'm not sure if we need it for 1.0. 

In the best scenario, we can move shipping price estimation to a better place and adopt new controller implementation.

**Comment by mamazu** [comment]
That's what I thought too.

**Comment by pamil** [comment]
Thank you, Maximilian! 🎉

**Comment by mamazu** [comment]
Your welcome.

**Pull request merged**
