### PR TITLE
Fix token generator service for customer's password reset handler

### PR DESCRIPTION
**Pull request by diimpp**

### CODE REVIEW

**Comment by mamazu** [comment]
Could you please rebase it to the current master.

**Comment by lchrusciel** [comment]
Can we write some tests for it, so we can avoid regression in the future?

**Comment by mamazu** [comment]
How would you test something like this?

**Comment by lchrusciel** [comment]
I'm just wondering. Maybe check in the database if the field is set?

**Comment by lchrusciel** [comment]
Thanks, Dmitri! :tada:

**Comment by lchrusciel** [comment]
Anyway, it was added to https://github.com/Sylius/ShopApiPlugin/releases/tag/v1.0.0-rc.3

Enjoy! :)

**Pull request merged**
