### PR TITLE
[ENHANCEMENT] Added province code to AddressView

### PR DESCRIPTION
**Pull request by AndreasA**
Releates: #506 506

### CODE REVIEW

**Comment by mamazu** [comment]
First of all, thanks for your pull request. This is definitely an improvement. Currently we have two ways of handleing the address, one part is the view factory that you changed which affects how the addresses are rendered in the cart. The other part is the CRUD bundle, that renders the addresses with it's own logic (controlled by the serializer).

It would be nice if you could fix the tests and maybe also add one that checks that the cart now shows the correct address fields.

**Comment by AndreasA** [comment]
Sorry for not fixing the tests first but I had to exist my train. I will probably fix them tomorrow morning and add another test.

In regards to CRUD etc. from what I can tell everywhere else the provinceCode seems to work fine (when using my JS code with it). The only issue was the AddressView.

One thing though that is a bit `annoying` when saving an address (address book) you can only send either provinceCode (if the country has provinces assigned to it) or provinceName if the country does not have provinces assigned to it. Means unnecessary data changes when creating generalized code but that isn't that big an issue.

**Comment by AndreasA** [comment]
@mamazu Fixed the tests and added a test for address with province codes instead of province names.

**Comment by mamazu** [comment]
Thanks, this pull request looks great. :+1:

**Comment by mamazu** [comment]
Thank you, Andreas! :1st_place_medal:

**Pull request merged**
